<?php

namespace Database\Seeders;

use App\Models\Task;
use App\Models\NgoProfile;
use App\Models\Category;
use App\Models\Skill;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TaskSeeder extends Seeder
{
    public function run(): void
    {
        $ngos = NgoProfile::with('user')->get()->keyBy('organization_name');
        $categories = Category::pluck('id', 'name');
        $skills = Skill::pluck('id', 'name');

        if ($ngos->isEmpty()) {
            $this->command?->error('No NGOs found. Please run OrganizationSeeder first.');
            return;
        }

        $tasksData = [
            [
                'ngo' => 'Maiti Nepal',
                'category' => 'Community Service',
                'title' => 'Anti-Trafficking Community Outreach Campaign',
                'description' => 'Field awareness drive at transit points in Kathmandu to educate vulnerable youth and families on human trafficking red flags, emergency hotlines, and support resources.',
                'task_type' => 'Campaign',
                'selection_logic' => 'recommendation',
                'location' => 'Gaushala Bus Terminal, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7120,
                'longitude' => 85.3450,
                'required_volunteers' => 10,
                'start_date' => now()->addDays(5),
                'end_date' => now()->addDays(7),
                'application_deadline' => now()->addDays(4),
                'status' => 'Open',
                'urgency_level' => 'High',
                'skills' => ['Community Outreach', 'Communication', 'Leadership', 'Public Speaking'],
            ],
            [
                'ngo' => 'Maiti Nepal',
                'category' => 'Child Welfare',
                'title' => 'Rehabilitation Center Children Activity Day',
                'description' => 'Organizing creative art, music, and recreational activities for children in the shelter home to boost emotional wellbeing and social confidence.',
                'task_type' => 'Event',
                'selection_logic' => 'manual',
                'location' => 'Maiti Nepal Shelter, Pingalasthan, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7115,
                'longitude' => 85.3460,
                'required_volunteers' => 5,
                'start_date' => now()->subDays(10),
                'end_date' => now()->subDays(10),
                'application_deadline' => now()->subDays(12),
                'status' => 'Completed',
                'urgency_level' => 'Medium',
                'skills' => ['Child Care', 'Teaching', 'Communication'],
            ],
            [
                'ngo' => 'Room to Read Nepal',
                'category' => 'Education',
                'title' => 'Primary School Library Setup & Cataloging',
                'description' => 'Setting up child-friendly reading corners, sorting and cataloging Nepali children\'s books in primary schools in Pokhara.',
                'task_type' => 'Task',
                'selection_logic' => 'recommendation',
                'location' => 'Shree Janapriya Secondary School, Pokhara',
                'city' => 'Pokhara',
                'country' => 'Nepal',
                'latitude' => 28.2150,
                'longitude' => 83.9800,
                'required_volunteers' => 8,
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(14),
                'application_deadline' => now()->addDays(10),
                'status' => 'Open',
                'urgency_level' => 'Medium',
                'skills' => ['Tutoring', 'Teaching', 'Data Entry', 'Teamwork'],
            ],
            [
                'ngo' => 'Room to Read Nepal',
                'category' => 'Youth Development',
                'title' => 'Girls Education Mentorship Workshop',
                'description' => 'Life skills and mentorship training session for secondary school girls focusing on financial literacy, leadership, and higher education guidance.',
                'task_type' => 'Event',
                'selection_logic' => 'Weighted',
                'location' => 'Public Library Hall, Lalitpur',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'latitude' => 27.6750,
                'longitude' => 85.3200,
                'required_volunteers' => 6,
                'start_date' => now()->subDays(3),
                'end_date' => now()->addDays(2),
                'application_deadline' => now()->subDays(5),
                'status' => 'Ongoing',
                'urgency_level' => 'High',
                'skills' => ['Youth Empowerment', 'Public Speaking', 'Communication', 'Leadership'],
            ],
            [
                'ngo' => 'Possible Health (Nyaya Health Nepal)',
                'category' => 'Healthcare',
                'title' => 'Remote Rural Health Screening & Triage Camp',
                'description' => 'Mobile medical clinic in rural Achham providing general health checkups, blood pressure screenings, and basic triage support.',
                'task_type' => 'Emergency',
                'selection_logic' => 'recommendation',
                'location' => 'Bayalpata Hospital Compound, Achham',
                'city' => 'Achham',
                'country' => 'Nepal',
                'latitude' => 29.0400,
                'longitude' => 81.2500,
                'required_volunteers' => 12,
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(25),
                'application_deadline' => now()->addDays(15),
                'status' => 'Open',
                'urgency_level' => 'High',
                'skills' => ['First Aid', 'CPR', 'Triage', 'Healthcare', 'Health Education'],
            ],
            [
                'ngo' => 'Possible Health (Nyaya Health Nepal)',
                'category' => 'Mental Health',
                'title' => 'Community Mental Health Awareness & Support Group',
                'description' => 'Facilitating psychoeducation groups and reducing mental health stigma in rural communities across Sudurpashchim.',
                'task_type' => 'Campaign',
                'selection_logic' => 'manual',
                'location' => 'Sanfebagar Health Post, Achham',
                'city' => 'Achham',
                'country' => 'Nepal',
                'latitude' => 29.0550,
                'longitude' => 81.2800,
                'required_volunteers' => 4,
                'start_date' => now()->subDays(15),
                'end_date' => now()->subDays(12),
                'application_deadline' => now()->subDays(18),
                'status' => 'Completed',
                'urgency_level' => 'Medium',
                'skills' => ['Counselling', 'Mental Health Support', 'Psychological First Aid'],
            ],
            [
                'ngo' => 'Environment and Child Care Alliance Nepal (ECCA)',
                'category' => 'Environment',
                'title' => 'Bagmati Riverbank Cleanup & Reforestation Drive',
                'description' => 'Community waste collection, tree sapling plantation, and environmental awareness along the Bagmati corridor.',
                'task_type' => 'Campaign',
                'selection_logic' => 'auto_accept',
                'location' => 'Bagmati Corridor, Chabahil, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7180,
                'longitude' => 85.3490,
                'required_volunteers' => 20,
                'start_date' => now()->addDays(3),
                'end_date' => now()->addDays(3),
                'application_deadline' => now()->addDays(2),
                'status' => 'Open',
                'urgency_level' => 'Low',
                'skills' => ['Environmental Conservation', 'Reforestation', 'Waste Management', 'Teamwork'],
            ],
            [
                'ngo' => 'Environment and Child Care Alliance Nepal (ECCA)',
                'category' => 'Technology',
                'title' => 'School Solar Water Filtration IT System Setup',
                'description' => 'Installing water quality sensor monitoring systems and training local school teachers on digital maintenance logs.',
                'task_type' => 'Task',
                'selection_logic' => 'recommendation',
                'location' => 'Chabahil Secondary School, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7190,
                'longitude' => 85.3480,
                'required_volunteers' => 3,
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(16),
                'application_deadline' => now()->addDays(12),
                'status' => 'Draft',
                'urgency_level' => 'Low',
                'skills' => ['IT Support', 'Web Development', 'Data Entry'],
            ],
            [
                'ngo' => 'Nepal Red Cross Society',
                'category' => 'Disaster Relief',
                'title' => 'Monsoon Flood Emergency Relief Distribution',
                'description' => 'Distributing emergency food packages, clean water tablets, and tarpaulins to flood-affected families in Koshi province.',
                'task_type' => 'Emergency',
                'selection_logic' => 'recommendation',
                'location' => 'Disaster Relief Center, Biratnagar',
                'city' => 'Biratnagar',
                'country' => 'Nepal',
                'latitude' => 26.4525,
                'longitude' => 87.2718,
                'required_volunteers' => 15,
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(5),
                'application_deadline' => now()->subDays(3),
                'status' => 'Ongoing',
                'urgency_level' => 'High',
                'skills' => ['Disaster Response', 'Search and Rescue', 'First Aid', 'Logistics', 'Driving'],
            ],
            [
                'ngo' => 'Nepal Red Cross Society',
                'category' => 'Blood Donation',
                'title' => 'Kathmandu Valley Mega Blood Donation Drive',
                'description' => 'Coordinating blood donors, registration tables, refreshment stalls, and donor health screening at Bhrikutimandap.',
                'task_type' => 'Event',
                'selection_logic' => 'FCFS',
                'location' => 'Bhrikutimandap Exhibition Hall, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7020,
                'longitude' => 85.3170,
                'required_volunteers' => 12,
                'start_date' => now()->addDays(8),
                'end_date' => now()->addDays(8),
                'application_deadline' => now()->addDays(6),
                'status' => 'Open',
                'urgency_level' => 'High',
                'skills' => ['Blood Donation Drive', 'First Aid', 'Event Coordination', 'Communication'],
            ],
            [
                'ngo' => 'Teach For Nepal',
                'category' => 'Education',
                'title' => 'Public School Science Lab Equipment Assembly',
                'description' => 'Assisting TFN fellows in building low-cost practical science kits and setting up experiment tables in rural schools of Sindupalchowk.',
                'task_type' => 'Task',
                'selection_logic' => 'recommendation',
                'location' => 'Shree Seti Devi School, Chautara',
                'city' => 'Sindhupalchok',
                'country' => 'Nepal',
                'latitude' => 27.7780,
                'longitude' => 85.7170,
                'required_volunteers' => 6,
                'start_date' => now()->addDays(18),
                'end_date' => now()->addDays(20),
                'application_deadline' => now()->addDays(14),
                'status' => 'Open',
                'urgency_level' => 'Medium',
                'skills' => ['Teaching', 'Construction', 'Teamwork'],
            ],
            [
                'ngo' => 'Teach For Nepal',
                'category' => 'Youth Development',
                'title' => 'Fellowship Orientation Logistics & Media',
                'description' => 'Event photography, audio-visual support, and registration desk management for the new batch of 50 TFN teaching fellows.',
                'task_type' => 'Event',
                'selection_logic' => 'manual',
                'location' => 'Staff College, Jawalakhel, Lalitpur',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'latitude' => 27.6720,
                'longitude' => 85.3130,
                'required_volunteers' => 4,
                'start_date' => now()->subDays(20),
                'end_date' => now()->subDays(19),
                'application_deadline' => now()->subDays(22),
                'status' => 'Completed',
                'urgency_level' => 'Low',
                'skills' => ['Photography', 'Videography', 'Event Coordination', 'Logistics'],
            ],
            [
                'ngo' => 'Karuna Foundation Nepal',
                'category' => 'Elderly Care',
                'title' => 'Inclusive Municipality Accessibility Assessment Survey',
                'description' => 'Field survey mapping public ramp access, wheelchair facilities, and disability barriers across municipal offices in Jhapa.',
                'task_type' => 'Task',
                'selection_logic' => 'recommendation',
                'location' => 'Bhadrapur Municipality Office, Jhapa',
                'city' => 'Bhadrapur',
                'country' => 'Nepal',
                'latitude' => 26.5440,
                'longitude' => 88.0940,
                'required_volunteers' => 8,
                'start_date' => now()->addDays(10),
                'end_date' => now()->addDays(13),
                'application_deadline' => now()->addDays(7),
                'status' => 'Open',
                'urgency_level' => 'Medium',
                'skills' => ['Community Outreach', 'Data Entry', 'Communication'],
            ],
            [
                'ngo' => 'Karuna Foundation Nepal',
                'category' => 'Healthcare',
                'title' => 'Cerebral Palsy Physical Therapy & Family Support Camp',
                'description' => 'Assisting pediatric physiotherapists during community rehabilitation sessions for children living with cerebral palsy.',
                'task_type' => 'Event',
                'selection_logic' => 'manual',
                'location' => 'Disability Rehabilitation Center, Pulchowk',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'latitude' => 27.6780,
                'longitude' => 85.3190,
                'required_volunteers' => 5,
                'start_date' => now()->subDays(1),
                'end_date' => now()->addDays(3),
                'application_deadline' => now()->subDays(4),
                'status' => 'Ongoing',
                'urgency_level' => 'High',
                'skills' => ['Healthcare', 'First Aid', 'Child Care', 'Counselling'],
            ],
            [
                'ngo' => 'World Wildlife Fund Nepal (WWF Nepal)',
                'category' => 'Environment',
                'title' => 'Community Forest Wildlife Corridor Reforestation',
                'description' => 'Planting native trees to restore critical tiger and elephant corridor habitat in the Terai Arc Landscape.',
                'task_type' => 'Campaign',
                'selection_logic' => 'recommendation',
                'location' => 'Chitwan National Park Buffer Zone, Sauraha',
                'city' => 'Bharatpur',
                'country' => 'Nepal',
                'latitude' => 27.5830,
                'longitude' => 84.4950,
                'required_volunteers' => 15,
                'start_date' => now()->addDays(25),
                'end_date' => now()->addDays(27),
                'application_deadline' => now()->addDays(20),
                'status' => 'Open',
                'urgency_level' => 'Medium',
                'skills' => ['Environmental Conservation', 'Reforestation', 'Agriculture', 'Teamwork'],
            ],
            [
                'ngo' => 'World Wildlife Fund Nepal (WWF Nepal)',
                'category' => 'Environment',
                'title' => 'Snow Leopard Conservation Youth Media Contest',
                'description' => 'Designing digital infographics and reviewing community storytelling submissions celebrating mountain wildlife conservation.',
                'task_type' => 'Task',
                'selection_logic' => 'FCFS',
                'location' => 'WWF Nepal Office, Baluwatar, Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'latitude' => 27.7260,
                'longitude' => 85.3290,
                'required_volunteers' => 3,
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(35),
                'application_deadline' => now()->addDays(25),
                'status' => 'Draft',
                'urgency_level' => 'Low',
                'skills' => ['Social Media Management', 'Content Writing', 'Web Development'],
            ],
            [
                'ngo' => 'Dhulikhel Hospital (Kathmandu University Hospital)',
                'category' => 'Healthcare',
                'title' => 'Outreach Health Screening Clinic & Blood Pressure Drive',
                'description' => 'Assisting doctors and nurses at a day-long health screening camp in rural Kavrepalanchok.',
                'task_type' => 'Event',
                'selection_logic' => 'recommendation',
                'location' => 'Panchkhal Community Health Post, Kavre',
                'city' => 'Dhulikhel',
                'country' => 'Nepal',
                'latitude' => 27.6500,
                'longitude' => 85.6200,
                'required_volunteers' => 10,
                'start_date' => now()->addDays(7),
                'end_date' => now()->addDays(7),
                'application_deadline' => now()->addDays(5),
                'status' => 'Open',
                'urgency_level' => 'High',
                'skills' => ['Healthcare', 'First Aid', 'Triage', 'Health Education', 'Communication'],
            ],
            [
                'ngo' => 'Dhulikhel Hospital (Kathmandu University Hospital)',
                'category' => 'Food Distribution',
                'title' => 'Hospital Patient Nutrition & Meal Assistance',
                'description' => 'Helping prepare and distribute customized therapeutic meals to underprivileged inpatients in the ward.',
                'task_type' => 'Task',
                'selection_logic' => 'auto_accept',
                'location' => 'Dhulikhel Hospital Ward B, Dhulikhel',
                'city' => 'Dhulikhel',
                'country' => 'Nepal',
                'latitude' => 27.6220,
                'longitude' => 85.5560,
                'required_volunteers' => 4,
                'start_date' => now()->subDays(8),
                'end_date' => now()->subDays(6),
                'application_deadline' => now()->subDays(10),
                'status' => 'Cancelled',
                'urgency_level' => 'Low',
                'skills' => ['Food Distribution', 'Cooking', 'Community Service'],
            ],
            [
                'ngo' => 'Women\'s Rehabilitation Centre Nepal (WOREC)',
                'category' => 'Women Empowerment',
                'title' => 'Gender-Based Violence Legal Aid & Counselling Desk',
                'description' => 'Operating information desks, distributing pamphlet resources, and referring walk-in cases to legal counselors.',
                'task_type' => 'Campaign',
                'selection_logic' => 'recommendation',
                'location' => 'Balkumari Center, Lalitpur',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'latitude' => 27.6680,
                'longitude' => 85.3340,
                'required_volunteers' => 6,
                'start_date' => now()->addDays(14),
                'end_date' => now()->addDays(16),
                'application_deadline' => now()->addDays(11),
                'status' => 'Open',
                'urgency_level' => 'High',
                'skills' => ['Counselling', 'Community Outreach', 'Public Speaking', 'Communication'],
            ],
            [
                'ngo' => 'Women\'s Rehabilitation Centre Nepal (WOREC)',
                'category' => 'Administration',
                'title' => 'Women Livelihood Micro-Enterprise Survey & Data Entry',
                'description' => 'Digitizing field survey questionnaires collected from women self-help groups across 4 districts.',
                'task_type' => 'Task',
                'selection_logic' => 'FCFS',
                'location' => 'WOREC Head Office, Balkumari, Lalitpur',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'latitude' => 27.6685,
                'longitude' => 85.3345,
                'required_volunteers' => 5,
                'start_date' => now()->subDays(12),
                'end_date' => now()->subDays(5),
                'application_deadline' => now()->subDays(14),
                'status' => 'Completed',
                'urgency_level' => 'Low',
                'skills' => ['Data Entry', 'Accounting', 'IT Support'],
            ],
        ];

        foreach ($tasksData as $tData) {
            $ngo = $ngos->get($tData['ngo']);
            if (!$ngo) continue;

            $categoryId = $categories->get($tData['category']);
            if (!$categoryId) continue;

            $slug = Str::slug($tData['title']);

            $task = Task::updateOrCreate(
                ['slug' => $slug],
                [
                    'ngo_id'               => $ngo->id,
                    'category_id'          => $categoryId,
                    'title'                => $tData['title'],
                    'description'          => $tData['description'],
                    'task_type'            => $tData['task_type'],
                    'selection_logic'      => $tData['selection_logic'],
                    'location'             => $tData['location'],
                    'city'                 => $tData['city'],
                    'country'              => $tData['country'],
                    'latitude'             => $tData['latitude'],
                    'longitude'            => $tData['longitude'],
                    'required_volunteers'  => $tData['required_volunteers'],
                    'start_date'           => $tData['start_date'],
                    'end_date'             => $tData['end_date'],
                    'application_deadline' => $tData['application_deadline'],
                    'status'               => $tData['status'],
                    'urgency_level'        => $tData['urgency_level'],
                    'created_by'           => $ngo->user_id,
                ]
            );

            // Sync skills
            $skillIds = [];
            foreach ($tData['skills'] as $skillName) {
                if (isset($skills[$skillName])) {
                    $skillIds[] = $skills[$skillName];
                }
            }
            $task->skills()->sync($skillIds);
        }

        $this->command?->info('TaskSeeder executed successfully: 20 realistic tasks seeded.');
    }
}
